# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CbersExplorer
                                 A QGIS plugin
 CBERS Explorer is a plugin designed to help find images from CBERS-4A/WPM - Multispectral and Panchromatic Bands Fusioned.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-18
        copyright            : (C) 2024 by Tharles de Sousa Andrade
        email                : irtharles@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CbersExplorer class from file CbersExplorer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cbers_explorer import CbersExplorer
    return CbersExplorer(iface)
